### ISSUE TITLE
It's all shit

### ISSUE THREAD

**Issue by kallangerard** [t04glovern/linkedin-professional#1]
Quality is not someone else's problem

**Comment by t04glovern** [comment]
thank you for your feedback 

I think that io-ts are blank and k6 should strive to be more flimsy because they were originally built as something else:

The only thing i can think of atm is to delete the sideboard which uses those generic bytes, and generate generic names by iterating through various pieces.

Update:

I guess that we have more than just a rectangular toosbif. There's a bit at the front that matches some top nibbles at the base. And a horizontal one (top or bottom?). I'm not sure what to do with them.

**Comment by kallangerard** [comment]
Can't argue with that logic
